version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: openbiz
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  api:
    build: ./apps/api
    depends_on:
      - db
    environment:
      - PORT=4000
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/openbiz?schema=public
      - BYPASS_OTP=123456
    ports:
      - "4000:4000"
    volumes:
      - ./apps/api:/usr/src/app
      - ./schema:/usr/src/schema
      - ./prisma:/usr/src/prisma
  web:
    build: ./apps/web
    depends_on:
      - api
    environment:
      - VITE_API_BASE=http://localhost:4000
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/usr/src/app
      - ./schema:/usr/src/schema
volumes:
  dbdata:
